[build]
  command = "npm run build"
  functions = "functions"  # Specify where serverless functions are located
  publish = "dist"         # Publish directory

[dev]
  framework = "vite"
  targetPort = 3003
  port = 8888

[[redirects]]
  from = "/generate-tarot-story"
  to = "/.netlify/functions/generate-tarot-story" # Route API to the function
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/tarot_descriptions.json"
  to = "/tarot_descriptions.json"
  status = 200
