[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"  # Use your Vite dev script
  targetPort = 3000
  port = 8888
  publish = "public"
