[dev]
  framework = "vite"
  targetPort = 3003 # Port where Vite serves the frontend
  port = 8888       # Netlify proxy port

[[redirects]]
  from = "/generate-tarot-story"
  to = "http://localhost:3003/generate-tarot-story" # Proxy to Express server
  status = 200
